### ISSUE TITLE
redis-operator not reachable webhook

### ISSUE THREAD

**Issue by dntosas** [OT-CONTAINER-KIT/helm-charts#137]
**Does this issue reproduce with the latest release?**
Yes
**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
```
Error from server: conversion webhook for redis.redis.opstreelabs.in/v1beta1, Kind=RedisCluster failed: Post "https://XXX.svc:443/convert?timeout=30s": dial tcp XXX:443: connect: connection refused
```

checked that there are healthy endpoints on this service

**What did you expect to see?**

**What did you see instead?**

**Comment by jwitko** [comment]
It appears that the operator is forcing the service lookup to a hard-coded hostname as best I can tell.  Can't exactly tell where thats happening

**Comment by jwitko** [comment]
I see it now, its in the CRD:
https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/crds/redis-replication.yaml#L7719C1-L7727C25

**Comment by shubham-cmyk** [comment]
@jwitko 

Do you mean CA injection?

**Comment by jwitko** [comment]
> @jwitko
> 
> Do you mean CA injection?

No, The namespace for the webhook service is directly hard-coded into the CRDs.  Linked above.

**Comment by jwitko** [comment]
For example:
When I deploy redis-replication CRD I get:
```
conversion webhook for redis.redis.opstreelabs.in/v1beta1, Kind=RedisReplication failed: Post "https://webhook-service.redis-operator.svc:443/convert?timeout=30s": service "webhook-service" not found
```
If I remove the following section from the CRD:
```
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: webhook-service
          namespace: redis-operator
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1beta1
        - v1beta2
 ```
It works without issue.

**Comment by praveenperera** [comment]
I'm having the same issue

**Comment by Routhinator** [comment]
Confirming that 0.15.3 is the last working version of the chart, but also a note to others: You must delete the CRDs before downgrade for it to be successful.

**Comment by enigma-kazbek** [comment]
Downgrade works for me:
```bash
kubectl delete crd $(kubectl get crd | grep redis.opstreelabs.in | awk '{print $1}')
helm -n redis-operator un redis-operator
helm upgrade --install redis-operator ot-helm/redis-operator -n redis-operator --version 0.15.3
```

```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
  namespace: bcs-dev
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  securityContext:
    runAsUser: 1001
```
