### ISSUE TITLE
Toleration specified in value file not applied for Operator

### ISSUE THREAD

**Issue by Jaryllan** [OT-CONTAINER-KIT/helm-charts#165]
**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

**What did you do?**
`helm upgrade redis-operator ot-helm/redis-operator --install --namespace ot-operators --values values-operator.yaml --create-namespace`

values-operator.yaml content

```
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
nodeSelector:
  node-role.kubernetes.io/control-plane:
```

**What did you expect to see?**
Toleration applied.

**What did you see instead?**
Toleration not included.

Based on the value template. https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/values.yaml. It was suppose to be supported to supply toleration, but upon installing the operator, the toleration is not included
