### ISSUE TITLE
redis quote inside quote

### ISSUE THREAD

**Issue by amkartashov** [OT-CONTAINER-KIT/helm-charts#170]
https://github.com/OT-CONTAINER-KIT/helm-charts/blob/cfe2734d3f2894fd6c62b4143a5ac01855297e33/charts/redis/templates/redis-standalone.yaml#L18C1-L20

```yaml
    redisSecret:
      name: "{{ .Values.redisStandalone.redisSecret.secretName | quote }}"
      key: "{{ .Values.redisStandalone.redisSecret.secretKey | quote }}"
```

rendering with below values

```yaml
redisStandalone:
  redisSecret:
    secretName: redis-secret
    secretKey: password
```

will produce:

```yaml
# Source: redis/templates/redis-standalone.yaml
...
    redisSecret:
      name: ""redis-secret""
      key: ""password""
```
