### ISSUE TITLE
Liveness/readiness probes fail when redisSecret is set

### ISSUE THREAD

**Issue by diffuse** [OT-CONTAINER-KIT/helm-charts#172]
**Does this issue reproduce with the latest release?**
Yes, v0.15.11.

**What operating system and processor architecture are you using (`kubectl version`)?**
minikube `v1.30.1`.

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
client: 1.27.3

</pre></details>

**What did you do?**
I configured the cluster with a secret defined, e.g.
```yaml
redisCluster:
  clusterSize: 3
  clusterVersion: v7
  image: quay.io/opstree/redis
  tag: v7.0.12
  redisSecret:
    secretName: redis-secret
    secretKey: password
# ...snip...
```

**What did you expect to see?**
The cluster leader and follower pods to come up successfully.

**What did you see instead?**
The first redis cluster leader pod hangs at `0/1 Running`, then transitions to `CrashLoopBackOff`.  The output from `describe` on this pod shows that the liveness and readiness probes are failing because they can't authenticate:

```text
Liveness probe failed: AUTH failed: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user.

...snip...
```

```text
Readiness probe failed: AUTH failed: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user.

...snip...
```

**Comment by diffuse** [comment]
After further debugging, it turns out this was an issue with the values set in `podSecurityContext` and `redisCluster.securityContext`.

Everything works with the following values:
```yaml
redisCluster:
   # ..snip...
   securityContext:
     runAsUser: 1000
     runAsGroup: 1000
     fsGroup: 1000
   # ..snip..
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
```
Changing the values in either `podSecurityContext` OR `redisCluster.securityContext` to 1099 will reproduce the above issue.  I'm not sure at which point in the setup this starts creating issues, but the end result was that the leader pod was running redis in protected mode with no password configured.
