### ISSUE TITLE
Cannot add init container 

### ISSUE THREAD

**Issue by yash95shah** [OT-CONTAINER-KIT/helm-charts#184]
**Does this issue reproduce with the latest release?**
Yes
**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.29.1

</pre></details>

**What did you do?**
I am trying to pass in an input for init container using this value input to the helm chart (for testing) 
```
initContainer:
  enabled: true
  image: "alpine:3.8"
  imagePullPolicy: "Always"
  resources:
    requests:
      memory: "32Mi"
      cpu: "100m"
    limits:
      memory: "64Mi"
      cpu: "200m"
  env:
    - name: "ENV_VAR2"
      value: "value2"
  command: ["/bin/sh", "-c"]
  args: ["echo Hello, Helm!"]
```

**What did you expect to see?**
I expect the redis cluster resource and eventually statefulsets' pods to have this init container 
**What did you see instead?**
I get this error running the command `helm upgrade cluster-redis ot-helm/redis-cluster -f redis_conf.yaml -n ot-operators `

**Error: UPGRADE FAILED: template: redis-cluster/templates/redis-cluster.yaml:78:20: executing "redis-cluster/templates/redis-cluster.yaml" at <include>: wrong number of args for include: want 2 got 1**
