### ISSUE TITLE
Broken helm chart for redis-operator 0.10.0

### ISSUE THREAD

**Issue by eugene-chernyshenko** [OT-CONTAINER-KIT/helm-charts#20]
```
                        key:
                          type: string
  <<<<<<< HEAD
name:
  type: string
```

https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/crds/redis-cluster.yaml#L3427
