### ISSUE TITLE
redisCluster.leaderServiceType maybe should redisCluster.leader.ServiceType

### ISSUE THREAD

**Issue by willzhang** [OT-CONTAINER-KIT/helm-charts#43]
redisCluster.leaderServiceType --->redisCluster.leader.ServiceType

```
---
redisCluster:
  clusterSize: 3
  image: quay.io/opstree/redis
  tag: v6.2.5
  imagePullPolicy: IfNotPresent
  # redisSecret:
  #   secretName: redis-secret
  #   secretKey: password
  leader:
    replicas: 3
    serviceType: ClusterIP
```

and i have try `--set redisCluster.leaderServiceType` and `--set redisCluster.leader.ServiceType` , and the service Type still is ClusterIP
```
root@node01:/var/lib/sealos/data/default/rootfs# kubectl -n redis-operator  get svc
NAME                              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
redis-cluster-follower            ClusterIP   10.96.0.207   <none>        6379/TCP,9121/TCP   9m51s
redis-cluster-follower-headless   ClusterIP   None          <none>        6379/TCP            9m51s
redis-cluster-leader              ClusterIP   10.96.0.50    <none>        6379/TCP,9121/TCP   9m51s
redis-cluster-leader-headless     ClusterIP   None          <none>        6379/TCP            9m51s
```
