### ISSUE TITLE
Add CRD TLS options to helm charts

### ISSUE THREAD

**Issue by timvandruenen** [OT-CONTAINER-KIT/helm-charts#68]
Hi, thanks for all the great work you're doing!

Is it a good idea to add the TLS options which are available in the CRD in the helm charts as well?
TLS options in the CRD reference: https://ot-redis-operator.netlify.app/docs/crd-reference/redis-api/#tlsconfig

E.g. something like:
```
redisCluster:
  redisTLS:
    secretName: redis-tls-cert
    ca: ca.key
    cert: tls.crt
    key: tls.key
```
or
```
redisCluster:
  TLS:
    ca: ca.key
    cert: tls.crt
    key: tls.key
    secret:
      secretName: redis-tls-cert
```
