### ISSUE TITLE
TLS setup

### ISSUE THREAD

**Issue by haizafrog** [OT-CONTAINER-KIT/helm-charts#85]
Hi,

I want to add the TLS option while deploying redis-cluster and loading the certificates and the key from a secret.
Can you please add an example of how to set it up?

Thanks!!

**Comment by haizafrog** [comment]
When I declare it like that:
```
TLS:
  ca: ca.crt
  cert: tls.crt
  key: tls.key
  secret:
    secretName: tls-secret
```
 And the secret is declared like that:
```
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  ca.crt: |
           ...
  tls.crt: |
           ...
  tls.key: |
            ...
```
I get the attached error:
```
 redis-cluster-tls-leader 10:M 25 Mar 2023 01:48:53.963 # Failed to load certificate: /tls/tls.crt: error:0909006C:PEM routines:get_name:no start line
 redis-cluster-tls-leader 10:M 25 Mar 2023 01:48:53.963 # Failed to configure TLS. Check logs for more info.
```

Please advise.
Thanks!
