### ISSUE TITLE
Redis operator resource limits

### ISSUE THREAD

**Issue by sondrelg** [OT-CONTAINER-KIT/helm-charts#98]
Hi!

First of all, thanks for creating and/or maintaining this project. It's great :clap: 

Just came across this statistic:

![image](https://github.com/OT-CONTAINER-KIT/helm-charts/assets/25310870/bbff8c31-48ca-4edd-978e-794e85d52619)

Is it possible that the 500Mi requests/limit default in the redis-operator chart is overly aggressive? Seems to be for us, and I don't expect it to vary cluster to cluster.

**Comment by shubham-cmyk** [comment]
Maybe we could consider it to drop it to this level. 

```
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
```

What do you think ?
